### ISSUE TITLE
Tested this plugin on reveal js v5 and its working

### ISSUE THREAD

**Issue by abdulhakim-alshanqiti** [Martinomagnifico/reveal.js-fsfx#2]
i think it missleading to say that this plugin is for reveal js v4 now because the reader would think it can't work for reveal js 5 thank you for making this plugin

**Comment by abdulhakim-alshanqiti** [comment]
also if you are using npm you need to have  `window.Reveal = new Reveal({ your options })`

**Comment by Martinomagnifico** [comment]
Thanks. An update is planned :-)

**Comment by abdulhakim-alshanqiti** [comment]
very cool package !! i am currently using it to get reveal js on my university and i needed a way to fullscreen slides tried other plugins and they didn't work thanks for your help hopefully soon i will open source reveal js collaborative markdown editor so i can give back to ppl like you
